src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PostRepository::class)]
class Post
{
    const TYPES = ['Conciertos' => 'Conciertos', 'Eventos' => 'Eventos', 'Artistas' => 'Artistas', 'Bandas Sonoras' => 'Bandas Sonoras', 'Rock' => 'Rock'];

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $type = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $file = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $creation_date = null;

    #[ORM\Column(length: 255)]
    private ?string $url = null;

    #[ORM\ManyToOne(inversedBy: 'posts')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    /**
     * @var Collection<int, Interaction>
     */
    #[ORM\OneToMany(targetEntity: Interaction::class, mappedBy: 'post', orphanRemoval: true)]
    private Collection $interactions;

    public function __construct($title = null, $type = null, $description = null, $file = null, $url = null)
    {
        $this->title = $title;
        $this->type = $type;
        $this->description = $description;
        $this->file = $file;
        $this->creation_date = new \DateTime();
        $this->url = $url;
        $this->interactions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getFile(): ?string
    {
        return $this->file;
    }

    public function setFile(?string $file): static
    {
        $this->file = $file;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creation_date;
    }

    public function setCreationDate(\DateTimeInterface $creation_date): static
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): static
    {
        $this->url = $url;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Interaction>
     */
    public function getInteractions(): Collection
    {
        return $this->interactions;
    }

    public function addInteraction(Interaction $interaction): static
    {
        if (!$this->interactions->contains($interaction)) {
            $this->interactions->add($interaction);
            $interaction->setPost($this);
        }

        return $this;
    }

    public function removeInteraction(Interaction $interaction): static
    {
        if ($this->interactions->removeElement($interaction)) {
            // set the owning side to null (unless already changed)
            if ($interaction->getPost() === $this) {
                $interaction->setPost(null);
            }
        }

        return $this;
    }
}

src/Form/PostType.php
<?php

namespace App\Form;

use App\Entity\Post;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('type', ChoiceType::class, [
                'choices' => Post::TYPES
            ])
            ->add('description')
            ->add('file', FileType::class, ['label' => 'Photo', 'required' => false])
            ->add('submit', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Post::class,
        ]);
    }
}

src/Controller/PostController.php
<?php

namespace App\Controller;

use App\Entity\Post;
use App\Entity\User;
use App\Form\PostType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Knp\Component\Pager\PaginatorInterface;

class PostController extends AbstractController
{
    private $em;

    /**
     * @param EntityManagerInterface $em
     */
    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
    }

    #[Route('/post/{id}', name: 'app_post')]
    public function show($id): Response
    {
        if ($id <= 0) {
            return $this->redirect('/');
        }
        $post = $this->em->getRepository(Post::class)->find($id);
        if ($post) {
            return $this->render('post/post.html.twig', [
                'id' => $id,
                'post' => $post
            ]);
        } else {
            return $this->redirect('/');
        }
    }

    #[Route('/post-form', name: 'app_post_form')]
    public function index(Request $request, SluggerInterface $slugger, PaginatorInterface $paginator): Response
    {
        $post = new Post();
        $query = $this->em->getRepository(Post::class)->findAllPosts();

        $pagination = $paginator->paginate(
            $query,
            $request->query->getInt('page', 1),
            5
        );
        // minuto 16

        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $file = $form->get('file')->getData();
            $user = $this->em->getRepository(User::class)->find(1);
            $url = str_replace(" ", "-", $form->get('title')->getData());
            if ($file) {
                $originalFilename = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename . '-' . uniqid() . '.' . $file->guessExtension();
                try {
                    $file->move(
                        $this->getParameter('files_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    throw new \Exception('Ther is an error with your file');
                }
                $post->setFile($newFilename);
            }
            $post->setUser($user);
            $post->setUrl($url);
            $this->em->persist($post);
            $this->em->flush();
            return $this->redirectToRoute('app_post', ['id' => $post->getId()]);
        }
        return $this->render('post/index.html.twig', [
            'form' => $form->createView(),
            'posts' => $pagination
        ]);
    }

    #[Route('/insert/post/{id}', name: 'app_post_insert')]
    public function insert($id)
    {
        if ($id <= 0) {
            return $this->redirect('/');
        }
        $user = $this->em->getRepository(User::class)->find($id);
        if ($user) {
            $post = new Post(
                'Inserted Post For User ID: ' . $id,
                'Opinion',
                'Description Inserted Post',
                'Description File',
                'description-url'
            );
            $post->setUser($user);
            $this->em->persist($post);
            $this->em->flush();
            return new JsonResponse([
                'operation' => 'insert',
                'succes' => true,
                'creation_time' => (new \DateTime())->format('Y-m-d H:i:s')
            ]);
        } else {
            return $this->redirect('/');
        }
    }

    #[Route('/update/post/{id}', name: 'app_post_update')]
    public function update($id)
    {
        if ($id <= 0) {
            return $this->redirect('/');
        }
        $post = $this->em->getRepository(Post::class)->find($id);
        if ($post) {
            $post->setTitle('Updated Title');
            $this->em->flush();
            return new JsonResponse([
                'operation' => 'update',
                'succes' => true,
                'update_time' => (new \DateTime())->format('Y-m-d H:i:s')
            ]);
        } else {
            return $this->redirect('/');
        }
    }

    #[Route('/remove/post/{id}', name: 'app_post_remove')]
    public function remove($id)
    {
        if ($id <= 0) {
            return $this->redirect('/');
        }
        $post = $this->em->getRepository(Post::class)->find($id);
        if ($post) {
            $this->em->remove($post);
            $this->em->flush();
            return new JsonResponse([
                'operation' => 'remove',
                'succes' => true,
                'update_time' => (new \DateTime())->format('Y-m-d H:i:s')
            ]);
        } else {
            return $this->redirect('/');
        }
    }
}

templates/post/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}
	POST FORM
{% endblock %}
{% block body %}
	<style>

		.post-form {
			margin: 1em auto;
			max-width: 800px;
			font: 18px / 1.5 sans-serif;
		}
		form {
			border: 3px solid #000;
			padding: 1em;
			margin-bottom: 1em;
			background: #b2b2b2;
			border-radius: 20px;
		}
		#post div {
			margin: 10px 0;
			display: inline-flex;
			width: 100%;
		}
		#post div label,
		#post div button {
			display: inline-flex;
			width: 200px;
			margin-right: 30px;
		}
		#post div input,
		#post div textarea,
		#post div #post_creation_date {
			display: inline-flex;
			width: 220px;
		}
		.button-container {
			text-align: center;
			margin-top: 20px;
		}
		.button-container a,
		#post_submit {
			display: inline-block;
			padding: 10px 20px;
			background-color: #f4a338;
			color: white;
			text-decoration: none;
			border: none;
			border-radius: 5px;
			font: 18px / 1.5 sans-serif;
		}
		.button-container a:hover,
		#post_submit:hover {
			background-color: #d68f31;
		}
		table {
			border-collapse: collapse;
		}
		thead tr th,
		tbody tr td {
			border: 3px solid #ddd;
			padding: 0;
		}
		img {
			width: 100px;
			height: 100px;
			object-fit: cover;
		}
	</style>
	<div class="post-form">
		{{form(form)}}
			<div class="button-container">
				<a href="{{ path('app_main') }}">Go To Main</a>
			</div>
		</div>
		<table>
			<thead>
				<tr>
					<th>ID</th>
					<th>TITLE</th>
					<th>TYPE</th>
					<th>DESCRIPTION</th>
					<th>FILE</th>
					<th>CREATION DATE</th>
				</tr>
			</thead>
			{% for post in posts %}
				<tr>
					<td>
						<a href="{{path('app_post', {id:post.id})}}">{{post.id}}</a>
					</td>
					<td>{{post.title}}</td>
					<td>{{post.type}}</td>
					<td>{{post.description}}</td>
					<td><img src="{{asset('uploads/files/' ~ post.file)}}" alt="Not found"></td>
					<td>{{post.creation_date | date}}</td>
				</tr>
			{% endfor %}
		</table>
		<div class="navigation">
			{{knp_pagination_render(posts)}}
		</div>
	{% endblock %}

templates/post/post.html.twig
{% extends 'base.html.twig' %}
{% block title %}POST FORM
{% endblock %}
{% block body %}
	<style>/* .post-form {
			margin: 1em auto;
			max-width: 800px;
			width: 95%;
			font: 18px / 1.5 sans-serif;
		} */</style>
<div class="post-form">
	<h1>POST :
		{{id}}</h1>
	<p>TITLE :
		{{post.title}}</p>
	<p>TYPE :
		{{post.type}}</p>
	<p>DESCRIPTION :
		{{post.description}}</p>
	<p>URL :
		{{post.url}}</p>
	<p>DATE :
		{{ post.creationDate ? post.creationDate|date('Y-m-d H:i') : 'N/A' }}</p>
</div>{% endblock %}